/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infotech.estoque;

/**
 *
 * @author Gilberto-Notebook
 */
public class estoquePrincipal extends javax.swing.JInternalFrame {

    /**
     * Creates new form estoquePrincipal
     */
    public estoquePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdEstoque = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnEntradas = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        btnCategorias = new javax.swing.JMenuItem();
        btnItens = new javax.swing.JMenuItem();
        btnNotasFiscais = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnProdutosPendentes = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout jdEstoqueLayout = new javax.swing.GroupLayout(jdEstoque);
        jdEstoque.setLayout(jdEstoqueLayout);
        jdEstoqueLayout.setHorizontalGroup(
            jdEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jdEstoqueLayout.setVerticalGroup(
            jdEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        btnEntradas.setText("Entradas");
        jMenuBar1.add(btnEntradas);

        jMenu2.setText("Saidas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estoque Geral");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Administração Estoque");

        btnCategorias.setText("Categorias");
        jMenu4.add(btnCategorias);

        btnItens.setText("Itens");
        jMenu4.add(btnItens);

        btnNotasFiscais.setText("Notas Fiscais");
        jMenu4.add(btnNotasFiscais);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Relatorios");
        jMenuBar1.add(jMenu5);

        btnProdutosPendentes.setText("Produtos Pendentes");
        jMenuBar1.add(btnProdutosPendentes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jdEstoque))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jdEstoque))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCategorias;
    private javax.swing.JMenu btnEntradas;
    private javax.swing.JMenuItem btnItens;
    private javax.swing.JMenuItem btnNotasFiscais;
    private javax.swing.JMenu btnProdutosPendentes;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdEstoque;
    // End of variables declaration//GEN-END:variables
}
